### PR TITLE
Enable Secure Mode

### PR DESCRIPTION
**Pull request by mbbertino**
This should address #15, allowing optional enabling of secure mode.

### CODE REVIEW

**Comment by seawatts** [comment]
I think this can be achieved by using #30

**Comment by mbbertino** [comment]
@seawatts Hey that looks awesome! But I'm actually having problems with sending custom data through. 
This is what I'm doing, what am I missing?

``` javascript

setUserInIntercom(user) {
  let props = {
    'user.name': `User ${user.get('name')}`,
    'user.user_id': user.get('id'),
    'user.email': user.get('email'),
    'user.createdAt': user.get('createdAt'),
    'user.userHash': user.get('intercomUserHash')
  }

  this.get('intercom').setProperties(props)
},

**Comment by seawatts** [comment]
You have to call `this.get('intercom').update(props)` or `this.get('intercom').start(props)`

**Comment by mbbertino** [comment]
@seawatts Ah, thanks for that I'll try that soon and confirm it solves it ,then I'll close the issue and pr.

**Comment by mbbertino** [comment]
Alright @seawatts that seems to be working! The only change I had to make to make it work was the way I was creating props. It didn't respect the prop keys if they were "user.KEYNAME".

``` js
setUserInIntercom(user) {
  let intercom = this.get('intercom'),
      props = {
        name: user.get('name'),
        user_id: user.get('id'),
        email: user.get('email'),
        createdAt: user.get('createdAt'),
        userHash: user.get('intercomUserHash')
      }

  intercom.start(props)
},
```

**Pull request closed without merging**
